server:
  port: 8082

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/employeeDB
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernet:
       dialect: org.hibernate.dialect.MariaDBDialect
       
management:
  endpoints:
    web:
      exposure:
        include: "*"            
      
      